name: Build ThunderClientLibraries on Linux

on:
  push:
    # branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_call:

jobs:
  ThunderInterfaces:
    uses: rdkcentral/ThunderInterfaces/.github/workflows/Build ThunderInterfaces on Linux.yml@master

  ThunderClientLibraries:
    needs: ThunderInterfaces
    uses: VeithMetro/ThunderClientLibraries/.github/workflows/Linux build template.yml@development/actions
